### ISSUE TITLE
Crashed when scanning a big size docker image.

### ISSUE THREAD

**Issue by JackTien** [GitGuardian/ggshield#174]
**GitGuardian Shield Version**

-  I can reproduce this bug in the latest version

**Command executed**

`ggshield scan docker local-registry/repo-name/docker-ubuntu`

**Describe the bug**

We created a docker image whose size is 26GB and scanned secret by using this tool. However it returned error message as follows:
`Saving docker image... Traceback (most recent call last):
  File "/private/tmp/venv/lib/python3.8/site-packages/ggshield/docker.py", line 52, in docker_save_to_tmp
    subprocess.run(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['docker', 'save', 'local-registry/repo-name/docker-ubuntu', '-o', '/var/folders/vc/3g43_3rj0nz7gvpsyfnvdysw0000gn/T/tmpqz_ywf1iggshield/archive.tar']' timed out after 360 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/venv/bin/ggshield", line 8, in <module>
    sys.exit(cli_wrapper())
  File "/private/tmp/venv/lib/python3.8/site-packages/ggshield/cmd.py", line 229, in cli_wrapper
    return_code: int = cli.main(standalone_mode=False)
  File "/private/tmp/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/private/tmp/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/private/tmp/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/private/tmp/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/private/tmp/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/private/tmp/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/private/tmp/venv/lib/python3.8/site-packages/ggshield/docker.py", line 142, in docker_name_cmd
    return handle_exception(error, config.verbose)
  File "/private/tmp/venv/lib/python3.8/site-packages/ggshield/utils.py", line 271, in handle_exception
    raise e
  File "/private/tmp/venv/lib/python3.8/site-packages/ggshield/docker.py", line 127, in docker_name_cmd
    docker_save_to_tmp(name, archive, docker_timeout)
  File "/private/tmp/venv/lib/python3.8/site-packages/ggshield/docker.py", line 70, in docker_save_to_tmp
    raise click.ClickException('Command "{}" timed out'.format(" ".join(command)))
click.exceptions.ClickException: Command "docker save local-registry/repo-name/docker-ubuntu -o /var/folders/vc/3g43_3rj0nz7gvpsyfnvdysw0000gn/T/tmpqz_ywf1iggshield/archive.tar" timed out
`

**Expected behavior**

It should completely scan the image with no error occurring.

**Comment by agateau-gg** [comment]
Hi @JackTien. You can increase the timeout with the `--docker-timeout` option. For example running this command allows the scan to take up to an hour (3600 seconds):

```
ggshield scan docker --docker-timeout 3600 local-registry/repo-name/docker-ubuntu
```

**Comment by JackTien** [comment]
Thanks for the reply. It works, but I still get the following error messages:
>>  403:Quota limit reached.
Error scanning. Results may be incomplete.
The following chunk is affected:

**Comment by JackTien** [comment]
Ok. I’ll have a try for that. Tks.
