### ISSUE TITLE
ggshield v1.10.8 error with pre-commit

### ISSUE THREAD

**Issue by raja-soundaramourty** [GitGuardian/ggshield#189]
**GitGuardian Shield Version**

- [v1.10.8 ] I can reproduce this bug in the latest version in pre-commit 

**Command executed**

`pre-commit run --all`

**Describe the bug**

pre-commit config :
    - repo: https://github.com/gitguardian/gg-shield
      rev: v1.10.8
      hooks:
          - id: ggshield
            language_version: python3
            stages: [commit]

Throws below error 
GitGuardian Shield (pre-commit)..........................................Failed
- hook id: ggshield
- exit code: 1

Traceback (most recent call last):
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/bin/ggshield", line 5, in <module>
    from ggshield.cmd import cli_wrapper
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/lib/python3.10/site-packages/ggshield/cmd.py", line 167, in <module>
    @scan.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
Traceback (most recent call last):
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/bin/ggshield", line 5, in <module>
    from ggshield.cmd import cli_wrapper
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/lib/python3.10/site-packages/ggshield/cmd.py", line 167, in <module>
    @scan.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
Traceback (most recent call last):
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/bin/ggshield", line 5, in <module>
    from ggshield.cmd import cli_wrapper
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/lib/python3.10/site-packages/ggshield/cmd.py", line 167, in <module>
    @scan.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
Traceback (most recent call last):
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/bin/ggshield", line 5, in <module>
    from ggshield.cmd import cli_wrapper
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/lib/python3.10/site-packages/ggshield/cmd.py", line 167, in <module>
    @scan.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
Traceback (most recent call last):
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/bin/ggshield", line 5, in <module>
    from ggshield.cmd import cli_wrapper
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/lib/python3.10/site-packages/ggshield/cmd.py", line 167, in <module>
    @scan.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
Traceback (most recent call last):
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/bin/ggshield", line 5, in <module>
    from ggshield.cmd import cli_wrapper
  File "/home/vscode/.cache/pre-commit/repoardqn2eq/py_env-python3/lib/python3.10/site-packages/ggshield/cmd.py", line 167, in <module>
    @scan.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?

**Expected behavior**

Works Correctly

**Screenshots**

NA

**Traceback (if available)**

if v1.10.8 is changed to main works correctly

**Comment by agateau-gg** [comment]
Hi Raja, thank you for this report.

We just released ggshield 1.11.0, which fixes it. Please reopen this issue if it is not the case.
