### ISSUE TITLE
`ggshield auth login` error: `RuntimeError: dictionary changed size during iteration`

### ISSUE THREAD

**Issue by iainsproat** [GitGuardian/ggshield#318]
**GitGuardian Shield Version**

- [x] I can reproduce this bug in the latest version

**Command executed**

```shell
ggshield auth login
```

**Describe the bug**
I'm a new user and wish to install ggshield CLI on my mac.

On my mac (macOS monterey 12.5), I installed ggshield via `brew install gitguardian/tap/ggshield`

This installed version 1.13.0.
```shell
ggshield --version
ggshield, version 1.13.0
```

I then ran `ggshield auth login` and received the following error:

```shell
Traceback (most recent call last):
  File "/opt/homebrew/bin/ggshield", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/ggshield/cmd/main.py", line 156, in main
    return cli.main(args, prog_name="ggshield", standalone_mode=not show_crash_log)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/ggshield/cmd/main.py", line 117, in cli
    config = Config(config_path)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/ggshield/core/config/config.py", line 40, in __init__
    self.user_config, self._config_path = UserConfig.load(config_path=config_path)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/ggshield/core/config/user_config.py", line 144, in load
    user_config._update_from_file(local_config_path)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/ggshield/core/config/user_config.py", line 167, in _update_from_file
    obj = UserV1Config.load_v1(data)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/ggshield/core/config/user_config.py", line 215, in load_v1
    UserV1Config.matches_ignore_to_dict(data)
  File "/opt/homebrew/Cellar/ggshield/1.13.0/libexec/lib/python3.9/site-packages/ggshield/core/config/user_config.py", line 262, in matches_ignore_to_dict
    for idx, match in enumerate(matches_ignore):
RuntimeError: dictionary changed size during iteration
```

This is consistent behaviour,  running `ggshield auth login` multiple times results in the same error message.

**Expected behavior**

I was expecting to login and not be presented with any errors.

**Screenshots**

**Traceback (if available)**

**Comment by agateau-gg** [comment]
Hi,

This bug is odd. I am going to need a bit more information about it:

- What Python version do you use?
- Do you have a .gitguardian.yml (or similar) in the directory you run the command or in your home directory, which would contain a `matches-ignore` entry in it?

**Comment by agateau-gg** [comment]
Ah, I can reproduce the issue with this `.gitguardian.yml` file:

```yaml
matches_ignore:
  name: foo
  match: 0123456789abcdef
```

The problem here is that `matches_ignore` is supposed to be a list, not a mapping. To fix it the file would need to be changed to this:

```yaml
matches_ignore:
  - name: foo
    match: 0123456789abcdef
```

Let me know if this helps.

**Comment by iainsproat** [comment]
Hi, thanks for investigating this - your suggestion resolved the issue 🥳 . The `.gitguardian` file was indeed a map instead of a list.

**Comment by agateau-gg** [comment]
Good to hear! Closing the issue then.
