### ISSUE TITLE
Make core.config.utils.load_yaml check the type of the loaded data

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#377]
## Environment

- ggshield version: 1.13.3

## Describe the bug

When a .gitguardian.yml file contains a valid YAML document, but this document is not a dictionary, the user gets a puzzling error message.

Steps to reproduce:

1. Create a .gitguardian.yml file containing `Hello` (A valid YAML document containing a *string*)
2. Run any ggshield command, for example `ggshield quota`

Actual result:

ggshield fails with an error like this:

```
$ ggshield quota
Traceback (most recent call last):
  File "/home/agateau/.local/bin/ggshield", line 8, in <module>
    sys.exit(main())
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/ggshield/cmd/main.py", line 160, in main
    return cli.main(args, prog_name="ggshield", standalone_mode=not show_crash_log)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/ggshield/cmd/main.py", line 121, in cli
    config = Config(config_path)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/ggshield/core/config/config.py", line 40, in __init__
    self.user_config, self._config_path = UserConfig.load(config_path=config_path)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/ggshield/core/config/user_config.py", line 144, in load
    user_config._update_from_file(local_config_path)
  File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/ggshield/core/config/user_config.py", line 157, in _update_from_file
    config_version = data.pop("version", 1)
AttributeError: 'str' object has no attribute 'pop'
https://github.com/GitGuardian/ggshield/issues/359
```

Expected result:

ggshield should report an error saying the configuration file is invalid.

**Comment by agateau-gg** [comment]
Fixed by #398.
