### ISSUE TITLE
ggshield secret scan repo aborts with little debugging information

### ISSUE THREAD

**Issue by aaronatp** [GitGuardian/ggshield#688]
## Environment

- ggshield version: 1.17.3, installed with homebrew
- Operating system: MacOS 13.4
- Python version: 3.11

## Describe the bug

I'm having the same problem as this closed issue (https://github.com/GitGuardian/ggshield/issues/446). "ggshield secret scan repo" aborts every time I run the following command. The debug info is:

"(base) user@Users-MacBook-Air ~ % ggshield secret scan repo https://github.com/chromium/chromium.git -v --show-secrets --debug
2023-08-13 20:55:58,441 DEBUG 8da2:7ff85b541640 ggshield.cmd.debug_logs:setup_debug_logs:44 args=['/usr/local/bin/ggshield', 'secret', 'scan', 'repo', 'https://github.com/chromium/chromium.git', '-v', '--show-secrets', '--debug']
2023-08-13 20:55:58,441 DEBUG 8da2:7ff85b541640 ggshield.cmd.debug_logs:setup_debug_logs:45 py-gitguardian=1.8.0
2023-08-13 20:55:58,446 DEBUG 8da2:7ff85b541640 ggshield.core.git_shell:git:80 command=['clone', 'https://github.com/chromium/chromium.git', '/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/tmp8ymy8_20']
Aborted!"

This is unfortunately of very little use to me - I would suggest: 1) making the debug and exit info more informative; and, 2) explaining what each mean in the documentation. I looked through both the documentation and code base for "Aborted!," and through the documentation for debug info, and could find very little.

Can you please help me identify the issue here?

EDIT: I learned that there is an environmental variable called GITGUARDIAN_CRASH_LOG that will print out the traceback after crashes. It seems like this should be a command line argument - that way users can find it easier (e.g., they would see it by typing "ggshield --help" rather than having to dig through the environmental variables).

The traceback is:

"(base) user@User-MacBook-Air-2 ggshield % ggshield secret scan repo https://github.com/chromium/chromium.git -v --show-secrets --debug
2023-08-13 22:13:41,274 DEBUG 8f23:7ff85b541640 ggshield.cmd.debug_logs:setup_debug_logs:44 args=['/usr/local/bin/ggshield', 'secret', 'scan', 'repo', 'https://github.com/chromium/chromium.git', '-v', '--show-secrets', '--debug']
2023-08-13 22:13:41,274 DEBUG 8f23:7ff85b541640 ggshield.cmd.debug_logs:setup_debug_logs:45 py-gitguardian=1.8.0
2023-08-13 22:13:41,281 DEBUG 8f23:7ff85b541640 ggshield.core.git_shell:git:80 command=['clone', 'https://github.com/chromium/chromium.git', '/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/tmp2wh86g8x']
Traceback (most recent call last):
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/ggshield/core/git_shell.py", line 81, in git
result = subprocess.run(
^^^^^^^^^^^^^^^
File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 550, in run
stdout, stderr = process.communicate(input, timeout=timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1209, in communicate
stdout, stderr = self._communicate(input, endtime, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 2109, in _communicate
self._check_timeout(endtime, orig_timeout, stdout, stderr)
File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1253, in _check_timeout
raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/usr/local/bin/git', 'clone', 'https://github.com/chromium/chromium.git', '/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/tmp2wh86g8x']' timed out after 45 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/ggshield", line 8, in
sys.exit(main())
^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/ggshield/cmd/main.py", line 147, in main
return cli.main(args, prog_name="ggshield", standalone_mode=not show_crash_log)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
return f(get_current_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/ggshield/cmd/secret/scan/repo.py", line 59, in repo_cmd
git(["clone", repository, tmpdirname])
File "/usr/local/Cellar/ggshield/1.17.3/libexec/lib/python3.11/site-packages/ggshield/core/git_shell.py", line 104, in git
raise click.Abort('Command "{}" timed out'.format(" ".join(command)))
click.exceptions.Abort: Command "clone https://github.com/chromium/chromium.git /var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/tmp2wh86g8x" timed out"

**Comment by agateau-gg** [comment]
Hi, looking at the code, we have a 45s timeout on all git commands. You reached it while cloning the repository. I agree with you the output could use some improvements. We are going to look into this.

Regarding the command you tried, you can workaround the issue by cloning the repository manually, then running `ggshield secret scan repo <path/to/your/clone>`. But it is important to understand `secret scan repo` scans *all commits* of the repository. In the case of Chromium this means scanning more than 1.3 million commits. This may not be what you want to do. If you instead want to scan the current state of the repository you can use `ggshield secret scan path -ry <path/to/your/clone>` (but keep in mind this scan would miss secrets committed in the past and then removed, so it's less secure than a repo scan)

**Comment by aaronatp** [comment]
Hi @agateau-gg thank you for your quick and thoughtful reply! I will have a look at the timeout options - this is good to know. The workaround you provide is also very helpful to know - thank you for suggesting it. I appreciate you highlighting the pros and cons of using a repo scan versus a path scan - I was actually (unrelatedly) curious about this a few hours ago, and this is also very good to know!
